apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jitsi
    stack: jicofo
  name: jicofo
spec:
  selector:
    matchLabels:
      app: jitsi
      stack: jicofo
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jitsi
        stack: jicofo
    spec:
      containers:
      - env:
        - name: JIBRI_XMPP_PASSWORD
          value: "{{ .Values.jibri.xmppPassword }}"
        - name: JIBRI_RECORDER_PASSWORD
          value: "{{ .Values.jibri.recorderPassword }}"
        - name: JIGASI_XMPP_PASSWORD
          value: "{{ .Values.jigasi.xmppPassword }}"
        - name: XMPP_SERVER
          value: prosody.jitsi.svc.cluster.local
        - name: XMPP_DOMAIN
          value: meet.jitsi
        - name: XMPP_AUTH_DOMAIN
          value: auth.meet.jitsi
        - name: JICOFO_COMPONENT_SECRET
          value: "{{ .Values.jicofo.componentSecret }}"
        - name: JICOFO_AUTH_USER
          value: "{{ .Values.jicofo.authUser }}"
        - name: JICOFO_AUTH_PASSWORD
          value: "{{ .Values.jicofo.authPassword }}"
        - name: JVB_BREWERY_MUC
          value: jvbbrewery
        - name: XMPP_INTERNAL_MUC_DOMAIN
          value: internal-muc.meet.jitsi
        - name: TZ
          value: "{{ .Values.timezone }}"
        image: "{{ .Values.jicofo.image }}"
        imagePullPolicy: "{{ .Values.jicofo.imagePullPolicy }}"
        name: jicofo
        resources: {}
      restartPolicy: Always
status: {}
